name: Run Telegram Bot

on:
  schedule:
    # Aqui você pode definir horários automáticos se quiser rodar sem precisar manual
    - cron: '0 9,13,16,20 * * *'  # executa às 9h, 13h, 16h e 20h UTC
  workflow_dispatch:  # permite rodar manualmente pelo GitHub

jobs:
  run-bot:
    runs-on: ubuntu-latest

    env:
      SHOPEE_AFFILIATE_URL: ${{ secrets.SHOPEE_AFFILIATE_URL }}
      SHOPEE_AFILIATE_URL: ${{ secrets.SHOPEE_AFILIATE_URL }}
      SHOPEE_API_KEY: ${{ secrets.SHOPEE_API_KEY }}
      SHOPEE_APP_ID: ${{ secrets.SHOPEE_APP_ID }}
      SHOPEE_APP_SECRET: ${{ secrets.SHOPEE_APP_SECRET }}
      SHOPEE_KEYWORDS: ${{ secrets.SHOPEE_KEYWORDS }}
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # ou a versão que você usa localmente

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Telegram Bot
        run: python telegram_bot.py
