- name: Executar script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          # Shopee - usar os nomes que você já tem
          SHOPEE_KEYWORDS: ${{ secrets.SHOPEE_KEYWORDS }}
          SHOPEE_APP_ID: ${{ secrets.SHOPEE_APP_ID }}
          SHOPEE_APP_SECRET: ${{ secrets.SHOPEE_APP_SECRET }}
          SHOPEE_AFFILIATE_URL: ${{ secrets.SHOPEE_AFILIATE_URL }}   # note o nome que você criou
          SHOPEE_API_KEY: ${{ secrets.SHOPEE_API_KEY }}
          SHOPEE_PARTNER: ${{ secrets.SHOPEE_PARTNER }}
        run: python telegram_bot.py
